import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/lib/CartContext";
import { Lexend } from "next/font/google";

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BHub",
  description: "Generated by BHub",
  icons: {
        icon: [
          {
            media: '(prefers-color-scheme: light)',
            url: '/b_hub_logo.png', // Path relative to public directory
          },
          {
            media: '(prefers-color-scheme: dark)',
            url: '/b_hub_logo.png', // Path relative to public directory
          },
        ],
      },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={lexend.className}
      >
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
